# Changes here will be overwritten by Copier
_commit: v0.0.85-10-gd009c10
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Template for creating a Static Website using Nuxt frontend hosted on
    AWS
install_claude_cli: false
python_ci_versions:
- 3.12.7
- 3.13.2
python_version: 3.12.7
repo_name: copier-nuxt-static-aws
repo_org_name: LabAutomationAndScreening
repo_org_name_for_copyright: LabAutomationAndScreening
ssh_port_number: 55734
template_might_want_to_install_aws_ssm_port_forwarding_plugin: false
template_uses_javascript: true
template_uses_pulumi: true
template_uses_python: true
template_uses_vuejs: true

