# Changes here will be overwritten by Copier
_commit: v0.0.4
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Template for creating a Static Website using Nuxt frontend hosted on
    AWS
python_ci_versions:
- 3.12.7
- 3.13.1
python_version: 3.12.7
repo_name: copier-nuxt-static-aws
ssh_port_number: 55734
template_uses_python: true

